### ISSUE TITLE
Cyclic redundancy check sum corruption on loading animation pngs

### ISSUE THREAD

**Issue by BrandonQuinn** [BrandonQuinn/MultiplayerShooter2D#4]
**Error**
sun.awt.image.PNGImageDecoder$PNGException: crc corruption
	at sun.awt.image.PNGImageDecoder.getChunk(Unknown Source)
	at sun.awt.image.PNGImageDecoder.getData(Unknown Source)
	at sun.awt.image.PNGImageDecoder.produceImage(Unknown Source)
	at sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
	at sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
	at sun.awt.image.ImageFetcher.run(Unknown Source)

**Code**
Image newImage = new ImageIcon(tmpImageFile.getPath()).getImage();
loadedAnimation.images.add(newImage);

at line 97 in AnimationLoader.java

**Notes**
it is to do with loading and writing out the data from the zip file, most likely.

**Comment by BrandonQuinn** [comment]
Problem fixed by reading input from the ZipEntry stream using the FileIO class.
